### ISSUE TITLE
Attempted to use catch-all token with token 7 of Undefined length [URGENT] (stopper)

### ISSUE THREAD

**Issue by ibrahim-m0unir** [DataAction/AdoNetCore.AseClient#231]
Sybase IQ
select any type of string or varchar data throws exception even if it is of length 1 or more
![image](https://github.com/DataAction/AdoNetCore.AseClient/assets/145011993/cc312284-160d-42f1-b7c9-7486021af070)

Stack Trace :
   at AdoNetCore.AseClient.Token.CatchAllToken.CalculateRemainingLength(Stream stream) in C:\Users\tiennguyen\source\repos\AdoNetCore.AseClient.0.19.2\src\AdoNetCore.AseClient\Token\CatchAllToken.cs:line 42
   at AdoNetCore.AseClient.Token.CatchAllToken.Read(Stream stream, DbEnvironment env, IFormatToken previous) in C:\Users\tiennguyen\source\repos\AdoNetCore.AseClient.0.19.2\src\AdoNetCore.AseClient\Token\CatchAllToken.cs:line 26
   at AdoNetCore.AseClient.Internal.TokenReader.<Read>d__0.MoveNext() in C:\Users\tiennguyen\source\repos\AdoNetCore.AseClient.0.19.2\src\AdoNetCore.AseClient\Internal\TokenReader.cs:line 37
   at AdoNetCore.AseClient.Internal.InternalConnection.InternalExecuteQueryAsync(AseCommand command, AseTransaction transaction, TaskCompletionSource`1 readerSource, CommandBehavior behavior) in C:\Users\tiennguyen\source\repos\AdoNetCore.AseClient.0.19.2\src\AdoNetCore.AseClient\Internal\InternalConnection.cs:line 342
--- End of stack trace from previous location ---
   at Dapper.SqlMapper.<ExecuteWrappedReaderImplAsync>d__64.MoveNext() in /_/Dapper/SqlMapper.Async.cs:line 1166
   at Program.<<<Main>$>g__ConnectToIQ|0_0>d.MoveNext() in D:\Projcs\SybaseIQ\SybaseIQ\Program.cs:line 14
   at Program.<<<Main>$>g__ConnectToIQ|0_0>d.MoveNext() in D:\Projcs\SybaseIQ\SybaseIQ\Program.cs:line 20
   at Program.<<Main>$>d__0.MoveNext() in D:\Projcs\SybaseIQ\SybaseIQ\Program.cs:line 6
   at Program.<Main>(String[] args)

**Comment by tangocoder** [comment]
I saw this error connecting to a Sybase IQ database, trying to read resultset of a query with string columns (I think you have the same issue)
I have created a fix: [manage TDS_DATA_COLUMNSTATUS in ValueReader #235](https://github.com/DataAction/AdoNetCore.AseClient/pull/235)
